---
- name: Add rsnapshot.conf symbolic link
  ansible.builtin.file:
    src: /usr/local/etc/rsnapshot.conf
    path: /etc/rsnapshot.conf
    state: link
    force: true

- name: Add SSH private key
  ansible.builtin.copy:
    content: "{{ puppeteers_backup_vbotka_rsnapshot_misc_ssh_private_key_content }}"
    dest: /root/.ssh/rsnapshot-private-ssh-key
    owner: root
    group: root
    mode: '0600'

- name: Add PATH to cron
  ansible.builtin.cron:
    name: PATH
    env: yes
    job: /bin:/usr/bin:/usr/sbin

- name: Add daily rsnapshot cronjob
  ansible.builtin.cron:
    name: "daily rsnapshot"
    job: "rsnapshot daily"
    hour: 2
    minute: 2

- name: Add weekly rsnapshot cronjob
  ansible.builtin.cron:
    name: "weekly rsnapshot"
    job: "rsnapshot weekly"
    hour: 3
    minute: 2
    weekday: 3

- name: Add monthly rsnapshot cronjob
  ansible.builtin.cron:
    name: "monthly rsnapshot"
    job: "rsnapshot monthly"
    hour: 4
    minute: 2
    day: 1
